#ifndef SWAY_UI_WIDGETS_ELEMENTPOSITIONS_HPP
#define SWAY_UI_WIDGETS_ELEMENTPOSITIONS_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(ui)

enum class ElementPosition : i32_t { RELATIVE, ABSOLUTE, FIXED, Latest };

NAMESPACE_END(ui)
NAMESPACE_END(sway)

#endif  // SWAY_UI_WIDGETS_ELEMENTPOSITIONS_HPP
