#ifndef SWAY_UI_WIDGET_LINEARLAYOUTORIENTATIONS_HPP
#define SWAY_UI_WIDGET_LINEARLAYOUTORIENTATIONS_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(ui)
NAMESPACE_BEGIN(widget)

enum class LinearLayoutOrientation : u32_t { HORZ, VERT };

NAMESPACE_END(widget)
NAMESPACE_END(ui)
NAMESPACE_END(sway)

#endif  // SWAY_UI_WIDGET_LINEARLAYOUTORIENTATIONS_HPP
