#ifndef SWAY_UI_WIDGET_TYPEDEFS_HPP
#define SWAY_UI_WIDGET_TYPEDEFS_HPP

#include <sway/core.hpp>

NS_BEGIN_SWAY()
NS_BEGIN(ui)

DECLARE_PTR_TYPES(Element)
DECLARE_PTR_TYPES(Widget)
DECLARE_PTR_TYPES(Button)
DECLARE_PTR_TYPES(Popup)
DECLARE_PTR_TYPES(Dialog)
DECLARE_PTR_TYPES(Draggable)
DECLARE_PTR_TYPES(Backdrop)
DECLARE_PTR_TYPES(DropTarget)
DECLARE_PTR_TYPES(Menu)
DECLARE_PTR_TYPES(MenuItem)

NS_END()  // namespace ui
NS_END()  // namespace sway

#endif  // SWAY_UI_WIDGET_TYPEDEFS_HPP
