#ifndef SWAY_UI_TYPES_HPP
#define SWAY_UI_TYPES_HPP

#include <sway/core.hpp>

NAMESPACE_BEGIN(sway)
NAMESPACE_BEGIN(ui)

DECLARE_CLASS_POINTER_TYPES(Builder)
DECLARE_CLASS_POINTER_TYPES(Painter)

NAMESPACE_END(ui)
NAMESPACE_END(sway)

#endif  // SWAY_UI_TYPES_HPP
